const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = __dirname;
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const mvp = fs.readFileSync(path.join(root, 'mvp.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'product.css'), 'utf8');
const productSystem = fs.readFileSync(path.join(root, 'product-system.css'), 'utf8');
const heroOil = fs.readFileSync(path.join(root, 'hero-oil-paint.css'), 'utf8');
const contract = fs.readFileSync(path.join(root, 'WEBSITE_EXPERIENCE_CONTRACT.md'), 'utf8');
const application = JSON.parse(fs.readFileSync(path.join(root, 'WEBSITE_VISUAL_MOTION_APPLICATION.json'), 'utf8'));

assert.match(index, /product\.css\?v=20260727-haika-step01-evidence-desk-r19/);
assert.match(index, /product-system\.css\?v=20260715-public-surfaces-r20/);
assert.ok(fs.existsSync(path.join(root, 'product-system.css')));
assert.match(index, /mvp-step02-r13\.js\?v=20260727-haika-step01-ui-skills-r7/);
assert.match(index, /mvp-step03-r1\.js\?v=20260727-source-truth-ledger-r16/);
assert.match(index, /app\.js\?v=20260727-source-truth-ledger-r16/);
assert.doesNotMatch(index, /product\.css\?v=20260713-n06-r3/);
assert.match(index, /vendor\/gsap-3\.13\.0\.min\.js/);
assert.match(index, /vendor\/gsap-flip-3\.13\.0\.min\.js/);
assert.ok(index.indexOf('vendor/gsap-3.13.0.min.js') < index.indexOf('app.js?v=20260727-source-truth-ledger-r16'));
assert.ok(index.indexOf('app.js?v=20260727-source-truth-ledger-r16') < index.indexOf('mvp-step02-r13.js?v=20260727-haika-step01-ui-skills-r7'));
assert.ok(fs.existsSync(path.join(root, 'vendor', 'gsap-3.13.0.min.js')));
assert.ok(fs.existsSync(path.join(root, 'vendor', 'gsap-flip-3.13.0.min.js')));
assert.ok(fs.existsSync(path.join(root, 'test_web_visual_motion_browser.spec.js')));
assert.ok(fs.existsSync(path.join(root, 'test_workbench_view_transition.js')));
assert.ok(fs.existsSync(path.join(root, 'test_workspace_draft_recovery.js')));
assert.match(mvp, /function canPlayStudioMotion\(\)/);
assert.match(mvp, /prefers-reduced-motion: reduce/);
assert.match(mvp, /function animateStudioEntry\(/);
assert.match(mvp, /function animateAssetSelection\(/);
assert.match(mvp, /function animateStoryboardSelection\(/);
assert.match(mvp, /function animateGuideFocus\(/);
assert.match(mvp, /workbenchMotionPlayed: false/);
assert.match(mvp, /if \(state\.workbenchMotionPlayed\) return;/);
assert.match(mvp, /workbenchReviews: \{\}/);
assert.match(mvp, /data-workbench-project=/);
assert.match(mvp, /function animateWorkbenchProjectSelection\(/);
assert.match(mvp, /window\.Flip\.getState\(flipTargets\)/);
assert.match(mvp, /function canUseWorkbenchViewTransition\(\)/);
assert.match(mvp, /document\.startViewTransition\(commit\)/);
assert.match(mvp, /history\.pushState\(null, '', '#' \+ nextHash\)/);
assert.match(mvp, /workbenchViewTransitionActive: false/);
assert.match(mvp, /function sanitizeProjectDetail\(\)/);
assert.match(mvp, /const hiddenLabels = new Set\(\['首个技能', '下一技能', '任务合同', '员工线程'\]\)/);
assert.match(mvp, /if \(statusLabels\.has\(text\)\) value\.textContent = humanizeProductionGate\(value\.textContent\)/);
assert.match(mvp, /return labels\[worker\.status\] \|\| '等待执行状态同步';/);
assert.match(mvp, /function productionStatusTone\(value\)/);
assert.match(mvp, /function productionStatusPill\(label, semanticValue = label\)/);
assert.match(mvp, /function focusWizardField\(formElement, openingFocus\)/);
assert.match(mvp, /focus\(\{preventScroll:true\}\)/);
assert.doesNotMatch(mvp, /setTimeout\(\(\) => form\.elements\.name\.focus\(\), 30\)/);
assert.match(mvp, /class="production-status-pill /);
assert.match(mvp, /productionStatusPill\(label, queued \? 'running' : decision\)/);
assert.match(mvp, /const selectedStatusPill = productionStatusPill\(selectedStatusLabel, selected\.status\)/);
assert.match(mvp, /const receiptPill = productionStatusPill\(/);
assert.match(mvp, /new EventSource\('\/api\/events\/projects'\)/);
assert.match(mvp, /projectEventPendingRevision/);
assert.match(mvp, /function renderWorkbenchAssetCatalog\(project\)/);
assert.match(mvp, /function renderWorkbenchAssetViewer\(\)/);
assert.match(index, /id="assetViewer"/);
assert.match(mvp, /function projectEventRevision\(event\)/);
assert.match(mvp, /projectEventSource\.addEventListener\('ready', recordProjectEventSignal\)/);
assert.match(mvp, /projectEventSource\.addEventListener\('keepalive', recordProjectEventSignal\)/);
assert.match(mvp, /function reconcileProjectEvents\(/);
assert.match(mvp, /function scheduleProjectEventRecovery\(/);
assert.match(mvp, /projectEventGapDetected/);
assert.match(mvp, /revision > state\.projectEventRevision \+ 1/);
assert.match(mvp, /if \(state\.loadingProjects\) \{\s*scheduleProjectEventRefresh\(\);/);
assert.match(mvp, /const draftStoragePrefix = 'niannian-ai:workspace-draft:v1'/);
assert.match(mvp, /function snapshotFormDraft\(/);
assert.match(mvp, /function restoreFormDraft\(/);
assert.match(mvp, /function restoreWizardFocus\(/);
assert.match(mvp, /window\.addEventListener\('keydown', event => \{[\s\S]*?closeScriptDramaWizard\(\)/);
assert.match(mvp, /aria-current="step"/);
assert.match(mvp, /function preserveCurrentStudioStageFocus\(kind\)/);
assert.match(mvp, /function restoreStudioStageFocus\(kind, stageId\)/);
assert.match(mvp, /function scriptN06ReferenceStateLabel\(state\)/);
assert.match(mvp, /confirmed_exact_sha:'已确认，可用于后续参考'/);
assert.match(mvp, /function scriptCandidateVersionLabel\(candidate\)/);
assert.match(mvp, /function scriptPromptForDisplay\(prompt\)/);
assert.doesNotMatch(mvp, /escapeHtml\(frameCandidate\.sha256\.slice\(0, 12\)\)/);
assert.match(mvp, /detail:sourceReady \? '当前原文已校验'/);
assert.doesNotMatch(mvp, /const sourceHash = source\.sha256/);
assert.match(mvp, /const labels = \[\.\.\.new Set\(values\.map\(humanizeProductionGate\)\)\];/);
assert.match(mvp, /function humanizeProjectNextAction\(value, fallback/);
assert.match(mvp, /humanizeProjectNextAction\(selectedRuntime\.nextAction/);
assert.doesNotMatch(mvp, /escapeHtml\(String\(selectedPreview\.sha256 \|\| ''\)\.slice\(0, 16\)/);
assert.match(mvp, /candidateDecisionDraftScope/);
assert.match(mvp, /clearSessionDraft\('redraw-project'\)/);
assert.match(mvp, /clearSessionDraft\('script-project'\)/);
assert.match(server, /text\/event-stream/);
assert.match(server, /writeProjectEvent\(client\.response, 'project-update', payload, revision\)/);
assert.match(server, /redrawProjectIds/);
assert.match(server, /scriptProjectIds/);
assert.match(mvp, /function workbenchRoute\(\)/);
assert.match(mvp, /function updateWorkbenchRoute\(\{transition = false\} = \{\}\)/);
assert.match(mvp, /workbenchActivities/);
assert.match(mvp, /data-workbench-tab="activity"/);
assert.match(mvp, /function renderWorkbenchActivity\(/);
assert.match(server, /SCRIPT_PROJECT_ACTIVITY_READY/);
assert.match(server, /async function loadPublicScriptProjectActivity\(/);
assert.match(mvp, /async function uploadScriptDocumentResumable\(file\)/);
assert.match(mvp, /X-NianNian-Chunk-SHA256/);
assert.match(mvp, /重新选择同一份文件/);
assert.match(server, /SCRIPT_UPLOAD_CHUNK_HASH_MISMATCH/);
assert.match(server, /SCRIPT_UPLOAD_INCOMPLETE/);
assert.match(server, /SCRIPT_PROJECT_CREATED_FROM_UPLOAD/);
assert.match(index, /重新选择同一文件即可继续已校验的上传内容/);
assert.match(mvp, /'\/project\/'/);
assert.match(mvp, /function renderScriptN06MediaPreview\(/);
assert.doesNotMatch(mvp, /media\.sha256\.slice/);
assert.match(mvp, /<video controls playsinline preload="metadata"/);
assert.match(mvp, /data-script-video-group=/);
assert.match(mvp, /function scriptN06ReviewSignature\(/);
assert.match(mvp, /function hydrateScriptN06Review\(/);
assert.match(mvp, /function isEditingScriptN06\(/);
assert.match(mvp, /hasVisibleN06Review/);
assert.match(mvp, /视频状态：/);
assert.doesNotMatch(mvp, /视频渠道：/);
assert.match(mvp, /const videoGroup = event\.target\.closest\('\[data-script-video-group\]'\)/);
assert.match(mvp, /const preservedScrollY = window\.scrollY;[\s\S]*?window\.scrollTo\(\{top:preservedScrollY, behavior:'auto'\}\)/);
assert.match(server, /serveScriptN06Media/);
assert.match(server, /SCRIPT_N06_MEDIA_HASH_MISMATCH/);
assert.match(server, /Content-Range/);
assert.match(app, /viewName\.startsWith\("workbench"\)/);
assert.match(mvp, /renderGuide\(\{animate:true\}\)/);
assert.match(mvp, /const preservedScrollY = animate \? window\.scrollY : null/);
assert.match(mvp, /window\.scrollTo\(\{top:preservedScrollY, behavior:'auto'\}\)/);
assert.match(mvp, /window\.Flip\.getState/);
assert.match(mvp, /data-flip-id/);
assert.match(mvp, /script-source-contract/);
assert.match(mvp, /从原文到可消费事实/);
assert.match(mvp, /原文锁定/);
assert.match(mvp, /data-storyboard-focus-panel/);
assert.match(mvp, /当前镜头组：/);
assert.match(mvp, /aria-pressed/);
assert.match(mvp, /animateStoryboardSelection\(flipState\)/);
assert.match(mvp, /const projectTypeFilter = document\.getElementById\('projectTypeFilter'\)/);
assert.match(mvp, /data-script-project-id/);
assert.match(mvp, /projectTypeFilter\?\.addEventListener\('change', renderProjects\)/);
assert.match(mvp, /state\.scriptProjects\.map\(project => \(\{\.\.\.project, projectKind:'script'\}\)\)/);
assert.match(mvp, /state\.studioMotionKey === key/);
assert.match(mvp, /if \(scriptRoute && !isEditingScriptCandidate\(scriptRoute\.projectId\)\)/);
assert.match(mvp, /\['02', '03'\]\.includes\(state\.scriptStudioStageId\) && !isEditingScriptCandidate\(projectId\)/);
assert.match(mvp, /window\.setInterval\(\(\) => \{\s*if \(!state\.user \|\| document\.hidden\) return;\s*refreshStep01ElapsedLabels\(\);\s*\}, 1000\)/);
assert.doesNotMatch(mvp, /refreshActiveRedrawProject\(\);\s*\}, 10000\)/);
assert.doesNotMatch(mvp, /if \(state\.user && !document\.hidden\) loadProjects\(\);/);
assert.doesNotMatch(mvp, /window\.scrollTo\(\{top:0/);
assert.match(app, /function setView\(viewName, \{ syncHash = true, scroll = "preserve" \} = \{\}\)/);
assert.match(app, /setView\(viewName, \{ syncHash: false, scroll: "preserve" \}\)/);
assert.match(app, /function syncHeroRenderer\(\)/);
assert.doesNotMatch(app, /workbenchCinemaTimeline/);
assert.doesNotMatch(app, /syncWorkbenchCinemaMotion/);
assert.match(app, /function animateTopLevelView\(panelName\)/);
assert.match(app, /animateTopLevelView\(panelName\)/);
assert.match(app, /const fluidCanvas = document\.querySelector\("#fluidCanvas"\)/);
assert.match(app, /let fluidRenderer = null/);
assert.match(app, /function createFluidRenderer\(canvas\)/);
assert.match(app, /canvas\.getContext\("webgl"/);
assert.match(app, /const createFallback = \(\) => \{/);
assert.match(app, /function initHeroRenderer\(\)/);
assert.match(app, /fluidRenderer\?\.stop\(\)/);
assert.doesNotMatch(app, /const heroVideo = document\.querySelector\("#heroVideo"\)/);
assert.match(app, /function syncVisualMotion\(\)/);
assert.match(app, /document\.body\.classList\.toggle\("is-showcase-view", panelName === "showcase"\)/);
assert.match(app, /function initShowcaseFilmMotion\(\)/);
assert.match(app, /--showcase-shift-x/);
assert.match(app, /visibilitychange", syncVisualMotion/);
assert.match(app, /removeEventListener\?\.\("change", syncVisualMotion\)/);
assert.match(css, /studio-motion-active/);
assert.match(css, /script-source-contract/);
assert.match(css, /guide-motion-active/);
assert.match(css, /overflow-anchor: none/);
assert.match(css, /view-motion-active/);
assert.match(css, /script-storyboard-current/);
assert.match(css, /script-storyboard-strip button\.is-active::after/);
assert.match(css, /guide-mode-switch/);
assert.match(css, /project-card-type/);
assert.match(css, /workbench-project-hub/);
assert.match(css, /workbench-project-grid/);
assert.match(css, /workbench-attention-rail/);
assert.match(css, /view-transition-name: niannian-workbench-inspector/);
assert.match(css, /::view-transition-new\(niannian-workbench-inspector\)/);
assert.match(css, /--nn-surface-canvas/);
assert.match(css, /\.production-status-pill\.is-ready/);
assert.match(css, /\.production-status-pill\.is-working/);
assert.match(css, /\.production-status-pill\.is-blocked/);
assert.match(css, /Shared state treatment inside the stage-level review surfaces/);
assert.match(productSystem, /--nn-font-ui/);
assert.match(productSystem, /--nn-accent/);
assert.match(productSystem, /\.workbench-project-card-copy strong/);
assert.match(productSystem, /\.script-n06-actionbar/);
assert.match(productSystem, /\.project-grid-live/);
assert.match(productSystem, /\.guide-layout/);
assert.match(productSystem, /\.team-grid/);
assert.match(productSystem, /grid-template-areas:\s*"member scope" "member next"/);
assert.match(productSystem, /\.team-facts\s*\{[\s\S]*?grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)/);
assert.match(productSystem, /\.project-grid-live\s*\{\s*grid-template-columns:\s*repeat\(auto-fill, minmax\(320px, 1fr\)\)/);
assert.match(productSystem, /\.project-card-visual,[\s\S]*?min-height:\s*68px;[\s\S]*?background:\s*var\(--nn-panel-quiet\)/);
assert.match(mvp, /CURRENT ACCOUNT/);
assert.match(mvp, /WORKSPACE BOUNDARY/);
assert.match(mvp, /<dt>项目<\/dt><dd>仅当前账户<\/dd>/);
assert.match(mvp, /<h3>继续创作<\/h3><p>选择项目，进入当前可执行步骤。<\/p>/);
assert.doesNotMatch(mvp, /项目与会话按当前登录账户隔离。/);
assert.match(mvp, /仅显示当前账户的项目与协作范围。/);
assert.doesNotMatch(mvp, /不在公开页面预填任何团队或项目数据/);
assert.doesNotMatch(mvp, /没有参考视频时，从可验证原文/);
assert.doesNotMatch(mvp, /已有源视频时，先还原证据/);
assert.doesNotMatch(mvp, /guideChecklist\.innerHTML = [^;]*flow\.description/);
assert.match(productSystem, /\.script-video-timeline > button:not\(\.is-active\)/);
assert.match(productSystem, /prefers-reduced-motion/);
assert.match(css, /\.script-video-timeline > button > \.production-status-pill/);
assert.match(css, /showcase-film-image/);
assert.match(css, /showcase-film-copy/);
assert.match(css, /#showcaseRedrawTitle/);
assert.match(css, /--showcase-shift-x/);
assert.match(css, /@media \(hover: hover\) and \(pointer: fine\)/);
assert.match(css, /Keep public page headers quiet/);
assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(contract, /不使用 ScrollSmoother 或 Lenis/);
assert.match(contract, /不得被动效打断/);
assert.match(contract, /GSAP Flip/);
assert.match(contract, /原文合同/);
assert.match(contract, /页面地图与信息层级/);
assert.match(contract, /视觉方向与资产/);
assert.match(contract, /已确认与待验证/);
assert.match(index, /id="projectTypeFilter"/);
assert.match(index, /id="guideModeSwitch"/);
assert.match(index, /id="guideChecklist"/);
assert.match(index, /aria-label="让角色、镜头与资产持续一致"/);
assert.match(index, /class="hero-logo"/);
assert.doesNotMatch(index, />AI 影像生产</);
assert.doesNotMatch(index, /把创意沿着真实制作流程推进成片。/);
assert.match(index, /id="heroVerb"/);
assert.match(index, /做高燃反转短剧/);
assert.doesNotMatch(index, /hero-route-deck/);
assert.match(index, /hero-oil-paint\.css\?v=20260723-fluid-hero-r1/);
assert.match(index, /<canvas id="fluidCanvas" aria-hidden="true"><\/canvas>/);
assert.doesNotMatch(index, /<video[\s\S]*?id="heroVideo"/);
assert.doesNotMatch(index, /niannian-hero-oil-vortex-loop-v2\.mp4/);
assert.doesNotMatch(index, />查看流程</);
assert.match(heroOil, /\.hero\s*\{[\s\S]*?background:\s*#050716;/);
assert.match(heroOil, /\.hero::before,[\s\S]*?\.hero::after\s*\{[\s\S]*?content:\s*none;[\s\S]*?animation:\s*none;/);
assert.match(heroOil, /#fluidCanvas\s*\{[\s\S]*?z-index:\s*0;[\s\S]*?pointer-events:\s*none;/);
assert.match(heroOil, /\.hero-logo\s*\{[\s\S]*?width:\s*104px;[\s\S]*?margin:\s*0 auto 18px;/);
assert.match(heroOil, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?#fluidCanvas[\s\S]*?display:\s*none;/);
assert.doesNotMatch(heroOil, /#heroVideo/);
assert.doesNotMatch(heroOil, /nn-oil-base-flow|nn-oil-texture-flow|mix-blend-mode:\s*soft-light/);
assert.doesNotMatch(heroOil, /filter:\s*blur/);
assert.match(heroOil, /\.hero-actions \.create-button\s*\{[\s\S]*?border-radius:\s*6px;[\s\S]*?background:\s*#f6539b;[\s\S]*?box-shadow:\s*none;/);
assert.match(heroOil, /\.hero h1\s*\{[\s\S]*?white-space:\s*normal;[\s\S]*?overflow-wrap:\s*anywhere;/);
assert.match(app, /initHeroRenderer\(\)/);
assert.match(app, /function canPlayHeroMotion\(\)[\s\S]*?currentView === "home"[\s\S]*?!document\.hidden[\s\S]*?prefers-reduced-motion: reduce/);
assert.match(app, /if \(canPlayHeroMotion\(\)\) fluidRenderer\.start\(\)/);
assert.match(app, /const heroWords = \["做高燃反转短剧", "做角色一致漫剧", "做连续真人短剧", "做高转化商品视频", "做电影感品牌片"\]/);
assert.doesNotMatch(index, /hero-input-tags/);
assert.match(index, /参考视频转绘/);
assert.match(index, /小说一键生成短剧/);
assert.match(index, /class="showcase-film"/);
assert.doesNotMatch(index, /让一个冲突发生在第一秒/);
assert.doesNotMatch(index, /让角色、场景和一张纸的重量/);
assert.doesNotMatch(index, /先还原每一个镜头发生了什么/);
assert.match(index, /assets\/showcase\/short-drama-keyart-v1\.png/);
assert.match(index, /assets\/showcase\/animation-drama-keyart-v1\.png/);
assert.match(index, /assets\/showcase\/redraw-keyart-partial-xuedi-v1\.png/);
assert.match(app, /function setShowcaseFilm\(nextIndex\)/);
assert.match(app, /function initShowcaseFilmDeck\(\)/);
assert.match(index, /data-open-script-drama-wizard/);
assert.match(index, /class="mobile-account-actions"/);
assert.match(index, /data-modal="register"/);
assert.match(index, /data-modal="enterprise"/);
assert.match(productSystem, /\.top-actions > \.account-control \{ display: block !important; \}/);
assert.match(productSystem, /\.top-actions \{ grid-column: 3; grid-row: 1; \}/);
assert.match(productSystem, /\.mobile-account-actions \{ grid-column: 1 \/ -1;/);
assert.doesNotMatch(index, /workbench-cinema-field/);
assert.match(index, /念念 AI \/ 制作中心/);
assert.match(index, /新建视频转绘/);
assert.match(index, /新建小说短剧/);
assert.match(mvp, /const projectStatusLabel = project =>/);
assert.match(mvp, /renderTeam\(\);\s*\/\/ Keep the creation entry usable[\s\S]*?renderWorkbench\(\);\s*loadSession\(\)/);
assert.match(mvp, /等待渠道登录/);
assert.match(mvp, /data-workbench-view="workbench"/);
assert.doesNotMatch(mvp, /workbench-route-summary/);
assert.match(app, /const heroWords = \["做高燃反转短剧", "做角色一致漫剧", "做连续真人短剧", "做高转化商品视频", "做电影感品牌片"\]/);
assert.equal(application.schema_version, 'niannian_website_visual_motion_application_v1');
assert.equal(application.authority.skill, 'web-visual-motion-planner');
assert.ok(application.source_repositories.some(item => item.source_id === 'web_visual_motion_planner' && item.application_status === 'applied'));
assert.ok(application.source_application_records.length >= 4);
const expectedRoutes = ['#home', '#projects', '#workbench', '#script/:id/stage/:id', '#redraw/:id/stage/:id', '#redraw-evidence/:id/shot/:id', '#showcase', '#guide', '#team'];
assert.deepEqual(application.route_coverage.map(item => item.route), expectedRoutes);
assert.ok(application.route_coverage.every(item => item.visual_protagonist && item.primary_action && item.motion && item.mobile_fallback && item.verification));
assert.ok(application.global_invariants.forbidden.includes('automatic_page_scroll'));

console.log(JSON.stringify({ok:true, verified:['local GSAP and Flip assets', 'stage-specific motion guard', 'source-contract boundary', 'asset-review Flip transition', 'candidate-editor refresh guard', 'guide-step focus transition', 'top-level view entry', 'no-scroll studio routing', 'offscreen hero renderer pause', 'reduced-motion fallback', 'native-scroll policy', 'browser regression entrypoint', 'full route coverage contract', 'source application records', 'experience contract']}));
